<?php require('template/header.phtml') ?>

<h2>Welcome to the IRIS Cloud Carbon FootPrint DashBoard </h2>

<!--<script>-->
<!--    // Use D3.js to render the graph-->
<!--    // You can customize this part based on the structure of your JSON data-->
<!--    var svg = d3.select('#graph-container').append('svg')-->
<!--        .attr('width', 400)-->
<!--        .attr('height', 200);-->
<!---->
<!--    svg.selectAll('rect')-->
<!--        .data(jsonData)-->
<!--        .enter().append('rect')-->
<!--        .attr('x', function(d, i) { return i * 50; })-->
<!--        .attr('y', function(d) { return 200 - d.value; })-->
<!--        .attr('width', 40)-->
<!--        .attr('height', function(d) { return d.value; })-->
<!--        .attr('fill', 'blue');-->
<!--</script>-->
<!--<div class="card-body"><canvas id="myPieChart" width="100%" height="50"></canvas></div>-->
<!--<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>-->
<!---->
<!--<div id="graph-container"></div>-->
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-chart-area me-1"></i>
        Area Chart Example
    </div>
    <div class="card-body"><canvas id="myAreaChart" width="100%" height="30"></canvas></div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
<!--<script type="text/javascript" src="mockData.json"></script>-->
<!--<script type="text/javascript" src="graphTest.js"></script>-->
<script src="js/chart-area-demo.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>

<?php require('template/footer.phtml') ?>


