<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

<!--    <link href="/css/my-style.css" rel="stylesheet">-->
    <link href="bootstrap-dashboard/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <title>IRIS Cloud Carbon Footprint Dashboard - <?php echo $view->pageTitle; ?></title>
    <script src="https://d3js.org/d3.v5.min.js"></script>
</head>

<body role=""document">

<div class="container">
        <div  class="row">
            <div id="title" class="col-xs-12">
                <img src="images/iris_logo.png" alt="Iris Logo" id="irisLogo"/>
                    <div> <h1><?php echo $view->pageTitle ?> </h1></div>


            </div>
        </div>


    <div class="row">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="index.php">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="aws.php">Add AWS Key</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="jsonDecode.php">Json decode test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="charts.php">Test chart</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

       <main id="content" class="col-xs-12">



